"""add picture to view

Revision ID: 3514031e88cc
Revises: 45f040462ecd
Create Date: 2025-10-16 22:29:17.674311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3514031e88cc"
down_revision: Union[str, None] = "45f040462ecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_view", sa.Column("picture_link", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_view", "picture_link")
    # ### end Alembic commands ###
