"""text is JSON now

Revision ID: 45f040462ecd
Revises: 457d8b3a1fa1
Create Date: 2025-10-16 21:51:02.477258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45f040462ecd"
down_revision: Union[str, None] = "457d8b3a1fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "filled_field",
        "text",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="text::json"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "filled_field",
        "text",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="text::text"
    )
    # ### end Alembic commands ###
