"""add message to view

Revision ID: 4c3b3033831d
Revises: 3514031e88cc
Create Date: 2025-10-16 22:38:32.936263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c3b3033831d"
down_revision: Union[str, None] = "3514031e88cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercise_view", sa.Column("message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_view", "message")
    # ### end Alembic commands ###
