"""add_exercise

Revision ID: a6ff7408cbe0
Revises: 2b7f6bfd7b94
Create Date: 2025-05-08 11:53:27.900317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6ff7408cbe0"
down_revision: Union[str, None] = "2b7f6bfd7b94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_structure",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("picture_link", sa.String(), nullable=False),
        sa.Column("linked_exercise_id", sa.Uuid(), nullable=True),
        sa.Column("field_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completed_exercise",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("hint", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "TEXT",
                "SLIDER",
                "CHOICE",
                "SELECTION",
                name="fieldtype",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("major", sa.Boolean(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("exercises", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filled_field",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("completed_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("exercises", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_exercise_id"], ["completed_exercise.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variants")
    op.drop_table("filled_field")
    op.drop_table("field")
    op.drop_table("completed_exercise")
    op.drop_table("exercise_structure")

    op.execute("DROP TYPE IF EXISTS fieldtype")
    # ### end Alembic commands ###
