"""added exercise_view

Revision ID: 8206290370da
Revises: ae01907e7528
Create Date: 2025-10-16 20:09:27.695154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8206290370da"
down_revision: Union[str, None] = "ae01907e7528"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_view",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("view", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("field", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table("exercise_view")
    # ### end Alembic commands ###
