"""Changed the theory

Revision ID: ae01907e7528
Revises: a6ff7408cbe0
Create Date: 2025-10-12 21:56:12.303343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae01907e7528"
down_revision: Union[str, None] = "a6ff7408cbe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_structure", sa.Column("time_to_read", sa.Integer(), nullable=False)
    )
    op.add_column(
        "exercise_structure", sa.Column("questions_count", sa.Integer(), nullable=False)
    )
    op.drop_column("exercise_structure", "field_count")
    op.add_column("field", sa.Column("view", sa.String(length=20), nullable=False))
    op.add_column("field", sa.Column("placeholder", sa.String(), nullable=True))
    op.add_column("field", sa.Column("prompt", sa.String(), nullable=True))
    op.add_column("field", sa.Column("name", sa.String(), nullable=False))
    op.alter_column(
        "field",
        "type",
        existing_type=postgresql.ENUM(
            "TEXT", "SLIDER", "CHOICE", "SELECTION", name="fieldtype"
        ),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_column("field", "hint")
    op.drop_column("field", "major")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field", sa.Column("major", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "field", sa.Column("hint", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "field",
        "type",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM(
            "TEXT", "SLIDER", "CHOICE", "SELECTION", name="fieldtype"
        ),
        existing_nullable=False,
    )
    op.drop_column("field", "name")
    op.drop_column("field", "prompt")
    op.drop_column("field", "placeholder")
    op.drop_column("field", "view")
    op.add_column(
        "exercise_structure",
        sa.Column("field_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("exercise_structure", "questions_count")
    op.drop_column("exercise_structure", "time_to_read")
    # ### end Alembic commands ###
