"""delete_question_id_column_from_answer_choice

Revision ID: 5e526ba7d65e
Revises: eb8039c1ebac
Create Date: 2025-03-02 15:43:22.742110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e526ba7d65e"
down_revision: Union[str, None] = "eb8039c1ebac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "answer_choice_question_id_fkey", "answer_choice", type_="foreignkey"
    )
    op.drop_column("answer_choice", "question_id")
    op.add_column(
        "question", sa.Column("answer_choice", sa.ARRAY(sa.UUID()), nullable=False)
    )
    op.alter_column("scale", "test_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("scale", "test_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("question", "answer_choice")
    op.add_column(
        "answer_choice",
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "answer_choice_question_id_fkey",
        "answer_choice",
        "question",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
