"""Added title in Filled_field

Revision ID: 457d8b3a1fa1
Revises: 8206290370da
Create Date: 2025-10-16 21:23:53.011129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "457d8b3a1fa1"
down_revision: Union[str, None] = "8206290370da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filled_field", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filled_field", "title")
    # ### end Alembic commands ###
