"""changed the theory

Revision ID: dbbb151c9b3e
Revises: 6cbef205be69
Create Date: 2025-09-21 10:38:14.520162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbbb151c9b3e"
down_revision: Union[str, None] = "6cbef205be69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'education_theme', 
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education_theme', 'tags')
    # ### end Alembic commands ###
