"""add major to field

Revision ID: 6062e055768b
Revises: 4c3b3033831d
Create Date: 2025-10-17 00:02:46.346732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6062e055768b"
down_revision: Union[str, None] = "4c3b3033831d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field", sa.Column("major", sa.Boolean(), nullable=False))
    op.add_column(
        "filled_field", sa.Column("view", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "filled_field", sa.Column("type", sa.String(length=20), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filled_field", "type")
    op.drop_column("filled_field", "view")
    op.drop_column("field", "major")
    # ### end Alembic commands ###
