"""create_inquiry_table

Revision ID: c875a3b15feb
Revises: 46baf81af9c3
Create Date: 2025-04-19 21:38:56.080822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.repositories.inquiry import InquiryRepository

# revision identifiers, used by Alembic.
revision: str = "c875a3b15feb"
down_revision: Union[str, None] = "46baf81af9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inquiry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("applications")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inquiry")
    # ### end Alembic commands ###
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("manager_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("online", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("problem_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "problem", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["users.id"], name="applications_client_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["users.id"], name="applications_manager_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="applications_pkey"),
    )